# Generated by Django 2.1 on 2019-07-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('título', models.CharField(max_length=256, unique=True)),
                ('genero', models.CharField(max_length=256)),
                ('ano', models.IntegerField()),
            ],
        ),
    ]
