# Generated by Django 2.1 on 2019-07-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='título',
            new_name='titulo',
        ),
    ]
