# Generated by Django 2.1 on 2019-07-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0002_auto_20190718_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='static/images/no-img.svg', upload_to='static/images'),
        ),
    ]
