# Generated by Django 2.1 on 2019-07-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0003_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, default='static/images/no-image.jpg', null=True, upload_to='teste/static/images/poster'),
        ),
    ]
