# Generated by Django 2.1 on 2019-07-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0005_auto_20190718_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/poster'),
        ),
    ]
