# Generated by Django 2.1 on 2019-07-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0006_auto_20190718_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
    ]
