# Generated by Django 2.1 on 2019-07-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0007_movie_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
