# Generated by Django 2.1 on 2019-07-29 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0012_auto_20190729_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='date_added',
            field=models.DateField(null=True, verbose_name='Adicionado em '),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='movies',
            field=models.ManyToManyField(related_name='users', through='teste.Favorite', to='teste.Movie', verbose_name='filmes'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste.UserProfile'),
        ),
    ]
